name: Firebase Hosting Deploy

on:
  push:
    branches:
      - main  # Only run on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the version of Node.js required by your project

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

    #  - name: Build
    #    run: npm run build

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_AUTODEPLOY_TOKEN }}
        run: firebase deploy --only hosting
